<script type="text/javascript">
	<%@ include file="/resources/js/RenderUtils.js" %>
	<%@ include file="/resources/js/Point.js" %>
	<%@ include file="/resources/js/Bounds.js" %>
	<%@ include file="/resources/js/GameObject.js" %>
	<%@ include file="/resources/js/WordCube.js" %>
	<%@ include file="/resources/js/TileLayout.js" %>
	<%@ include file="/resources/js/WordLayout.js" %>
	<%@ include file="/resources/js/AnswerLayout.js" %>
	<%@ include file="/resources/js/VerticalAnswerLayout.js" %>
	<%@ include file="/resources/js/ContinueButton.js" %>
	<%@ include file="/resources/js/ContinueDialog.js" %>
	<%@ include file="/resources/js/GameController.js" %>
	<%@ include file="/resources/js/InsertionGameController.js" %>
	<%@ include file="/resources/js/OmissionGameController.js" %>
	<%@ include file="/resources/js/SubstitutionGameController.js" %>
	<%@ include file="/resources/js/DerivationGameController.js" %>
	<%@ include file="/resources/js/SeparationGameController.js" %>
	<%@ include file="/resources/js/HardInsertionGameController.js" %>
	<%@ include file="/resources/js/TranspositionGameController.js" %>
	<%@ include file="/resources/js/ApplicationManager.js" %>
	<%@ include file="/resources/js/main.js" %>
</script>