<script type="text/javascript">
	<%@ include file="/WEB-INF/js/Point.js" %>
	<%@ include file="/WEB-INF/js/Bounds.js" %>
	<%@ include file="/WEB-INF/js/GameObject.js" %>
	<%@ include file="/WEB-INF/js/WordCube.js" %>
	<%@ include file="/WEB-INF/js/TileLayout.js" %>
	<%@ include file="/WEB-INF/js/WordLayout.js" %>
	<%@ include file="/WEB-INF/js/AnswerLayout.js" %>
	<%@ include file="/WEB-INF/js/VerticalAnswerLayout.js" %>
	<%@ include file="/WEB-INF/js/ContinueButton.js" %>
	<%@ include file="/WEB-INF/js/ContinueDialog.js" %>
	<%@ include file="/WEB-INF/js/GameController.js" %>
	<%@ include file="/WEB-INF/js/InsertionGameController.js" %>
	<%@ include file="/WEB-INF/js/OmissionGameController.js" %>
	<%@ include file="/WEB-INF/js/SubstitutionGameController.js" %>
	<%@ include file="/WEB-INF/js/DerivationGameController.js" %>
	<%@ include file="/WEB-INF/js/SeparationGameController.js" %>
	<%@ include file="/WEB-INF/js/ApplicationManager.js" %>
	<%@ include file="/WEB-INF/js/main.js" %>
</script>